module.exports={
    'HOST':'containers-us-west-183.railway.app',
    'USER':'root',
    'PASSWORD':'jt63M5Mpcz3O3bHt9sX4',
    'DB':'railway',
    'dialect':'mysql',
    'PORT':'6881',
    'pool':{
        'max':5,
        'min':0,
        'acquire':3000,
        'idle':1000,
    }
}